### ISSUE TITLE
deb dependency

### ISSUE THREAD

**Issue by mbnoimi** [filebot/filebot#10]
I suggest to add ```openjfx``` to FileBot *.deb dependencies as mentioned in issue  #9

**Comment by rednoah** [comment]
Please read this thread:
https://www.filebot.net/forums/viewtopic.php?f=11&t=4362

You're welcome to send in a patch that satisfies all the requirements listed here:
https://www.filebot.net/forums/viewtopic.php?f=11&t=4362#p24453
