### ISSUE TITLE
Umlauts in TV Show names don't work on thetvdb

### ISSUE THREAD

**Issue by joedemo42** [filebot/filebot#12]
Using filebot (installed by brew cask) to match a season of ["Sandmännchen"](http://thetvdb.com/?tab=series&id=272775&lid=14) using TheTVDB fails because of an XML error.

```
Invalid XML: SAXParseException: The element type "br" must be terminated by the matching end-tag "</br>".
<?xml version="1.0" encoding="UTF-8" ?>
<Data>
<Series>
<seriesid>272775</seriesid>
<language>de</language>
<SeriesName>Sandmännchen</SeriesName>
(etc)
```

**Comment by rednoah** [comment]
The `ä` looks just fine in the log. The error message says that the XML is invalid.
```
Invalid XML: SAXParseException: The element type "br" must be terminated by the matching end-tag "</br>".
```

Please report the issue on the TheTVDB forums so they can fix it:
https://forums.thetvdb.com/viewforum.php?f=5
