### ISSUE TITLE
Failure in test mode

### ISSUE THREAD

**Issue by ronisaacson** [filebot/filebot#20]
Using `filebot -script fn:amc --action test` with FileBot 4.7.9 (r4984), I get:

```
Rename movies using [TheMovieDB]
[TEST] From [XXX.avi] to [YYY.avi]
Processed 1 files
Finished without processing any files
Failure (°_°)
```

Note the inconsistency here. I don't think this should be considered a failure. (It wasn't in earlier versions of 4.7.)

**Comment by rednoah** [comment]
These operations are no longer added to the history. The amc script will have to be modified and keep track of what worked and what didn't instead of just checking the rename history at the end.

**Comment by rednoah** [comment]
Please try `-script dev:amc` and confirm that the latest changes fix the issue.

**Comment by ronisaacson** [comment]
That works. Thank you for the quick fix!
