### ISSUE TITLE
Query string manipulation

### ISSUE THREAD

**Issue by RikuXan** [filebot/filebot#21]
I have some TV shows where Filebot mismatches the files to the wrong show. For some of these, I'm able to define a filter rule that reads a file in which I keep the wrongly chosen matches (fortunately they're rather rare shows which I probably will never watch) and the correct match is chosen afterwards.

For some though, the correct show is not even found, since e.g. there is a year in the automatically detected query which is not in TVDB. I'm unable to manually set a query string since this is part of an automated system. Is there a possibility to manipulate automatically generated query strings on a rule basis (similar to what is achievable with the filter option)? If not, would this be a possible feature addition?

**Comment by rednoah** [comment]
I'll need the full file paths as text:
https://www.filebot.net/forums/viewtopic.php?f=3&t=1868

**Comment by RikuXan** [comment]
I'm using the CLI. This isn't really a help request though, I pretty much know what the issue is.

Say my file is named something like "some.series.name.2017.s01e01". Filebot's query auto detection makes [series, some series name 2017] out of this and (I assume) searches TheTVDB with these strings. It has a lot of hits for "series", being a relatively generic term and none for "some series name 2017", since TheTVDB has this show under "some series name", without the year. It then uses the top 5 results from the "series" search, the correct one not included.

In general, the auto detection functionality is working well enough for me, and I think it wouldn't be a good idea trying to cover all possible edge cases in there (especially when some release names are simply crude and bad). But making it possible to derive your own query strings based on self-defined rules would help out with exactly these edge cases. To return to the example, one possible solution would be having a list of user-supplied rules, consisting e.g. of a regex -> query string combination like ".*some.series.name.* -> some series name", that are tested before the auto-detection and either supplement or override it.

This is just a suggestion, it's totally fine if you evaluate the usefulness of this idea completely different than me, or don't want to take any feature requests at the time.

**Comment by rednoah** [comment]
I'd like to see the **logs** so I can have a clear picture of what's going on and what solutions there might be.

**Comment by RikuXan** [comment]
Here you go: https://gist.github.com/RikuXan/71b8312023865b70e40b1abd161b3f44

**Comment by rednoah** [comment]
The specific case of `Spring Break With Grandad` will magically start working 2-3 weeks down the line.

FileBot has it's own series index, but shows with 0 votes or bad ratings are not included. Now that I've given this show an extra 10 Star rating, it'll probably get picked up and indexed next time around.

**Comment by RikuXan** [comment]
Thanks for the help. But I assume this means you're not interested in a feature to supplement the series index with user-defined rules?

**Comment by rednoah** [comment]
Not really. The solution here would be to go to TheTVDB and give the show some ratings / votes. If it was a bit more popular, then it'd just work, for you and everyone else, regardless of whether or not TheTVDB search is feeling quirky today or not.

**Comment by rednoah** [comment]
Fix confirmed.

```
$ filebot -clear-cache
$ filebot -list --q "spring break with grandad 2017"
Spring Break With Grandad - 1x01 - Episode 1
Spring Break With Grandad - 1x02 - Episode 2
...
```
