### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bvblenny** [filebot/filebot#22]
I get the following error message: 
![error](https://cloud.githubusercontent.com/assets/22978217/25313782/f4997128-2835-11e7-962e-cb0edea0728c.PNG)

Steps to reproduce: 
I add some episodes to filebot, matching filenames works and then clicking 'Rename' produces the error (nothing is renamed).

System infos:
Windows 10 Pro 64-bit (newest 'creators update')
Java 8 Update 131
Filebot GUI 4.7.9 and 4.7.1 (both with the error) from [SourceForge](https://sourceforge.net/projects/filebot/files/filebot/FileBot_4.7.9/FileBot_4.7.9_x64.msi/download)

However this happens on one machine, I have another computer with the same OS and similar software (JDK 8 Update 60 + JRE 8 Update 111) and here it works just fine without error.

Seems like there is a Java class/package missing, any idea how to fix it?

Thanks

**Comment by rednoah** [comment]
Technical support is only available for users that purchase FileBot on the Windows Store.

This particular issue is a problem with your setup and can't happen if you use the Windows Store for deployment.
