### ISSUE TITLE
Doesn't work with samba shares mapped as network drive

### ISSUE THREAD

**Issue by Nottt** [filebot/filebot#23]
I'm trying to use FileBot with a folder that is shared to Windows with samba. I can rename,delete,create and move ok but FileBot fails to do the same.

See :  http://imgur.com/a/VuFcn

**Comment by rednoah** [comment]
1.
This might help:
https://www.filebot.net/forums/viewtopic.php?f=10&t=4881

2.
Have you tried to Google that error code?

**Comment by Nottt** [comment]
Tried all that and still nothing. The network drive is actually a FUSE
filesystem mounted on a linux box and shared with Windows.

I get  File.Open failed: can't open for read and write simultaneously, on
my mount.log.

On Mon, Apr 24, 2017 at 8:20 AM, Reinhard Pointner <notifications@github.com

**Comment by rednoah** [comment]
Have you tried a normal local filesystem as backend storage for the samba share?

**Comment by rednoah** [comment]
No reply.
