### ISSUE TITLE
Use the new TheTVDB JSON API instead of the old XML one

### ISSUE THREAD

**Issue by Thilas** [filebot/filebot#24]
Reporting [an issue on TheTVDB](https://forums.thetvdb.com/viewtopic.php?f=17&t=36909), I've been told that filebot should switch to the new REST JSON API.

According to [a post on their forum](https://forums.thetvdb.com/viewtopic.php?f=3&t=36557):
> We are planning to discontinue the old API as of October 1st, 2017

BTW, [a swagger documentation of the API](https://api.thetvdb.com/swagger) is available in order to help.

**Comment by rednoah** [comment]
The next major release will probably use the new API.

**Comment by rednoah** [comment]
You can try the latest jar which is configured with `TheTVDBv2`. Please give it some good testing and make sure it works and behaves the same way as the old XML API client.

**Comment by Thilas** [comment]
@rednoah, could you please the version to test please?

**Comment by rednoah** [comment]
Please read the `Announcements` section in the forums.
