### ISSUE TITLE
--def exec="@exec-format.txt" is broken in versions following 4.7.7 and further.

### ISSUE THREAD

**Issue by ArionMiles** [filebot/filebot#26]
This is what I have in `exec-format.txt` file:

`telegram.py -t "*{movie}{episode; n}*" -m "{movie; 'The movie'}_{episode; s00e00}{episode; ' - '}{episode; t}_ is ready."` but everything inside {} isn't passed into the program, meaning the movie/episode values aren't put into the program.

This is only observed while passing the arguments through `--def exec=` hook and in versions 4.7.7 and further.

**Comment by rednoah** [comment]
Please post the complete logs. `--def exec` works in all of my test cases.

**Comment by ArionMiles** [comment]
This is the complete log:

```

E:\New>filebot -script fn:amc --output "E:/" --action move --conflict skip -non-strict "E:/New" --log-file amc.log --def unsorted=y clean=y subtitles=en "seriesFormat=/TV Shows/{n}/{'Season '+s}/{s00e00} - {t }" --def "exec=@E:/New/args.txt" 
Locking C:\Users\%USERPROFILE%\AppData\Roaming\FileBot\logs\amc.log
Run script [fn:amc] at [Mon May 08 10:37:53 IST 2017]
Parameter: unsorted = y
Parameter: clean = y
Parameter: subtitles = en
Parameter: seriesFormat = /TV Shows/{n}/{'Season '+s}/{s00e00} - {t }
Parameter: exec = telegram.py -t "*{movie}{episode; n}*" -m "{movie; 'The movie'}_{episode; s00e00}{episode; ' - '}{episode; t}_ {movie; 'is ready.'}{episode; "is ready."}"
Argument[0]: E:\New
Ignore hidden: E:\New\args.txt
Ignore hidden: E:\New\args2.txt
Ignore hidden: E:\New\Manual.bat
Input: E:\New\Netflix.Iron.Fist.S01E01.Snow Gives Way..mkv
xattr: [Netflix.Iron.Fist.S01E01.Snow Gives Way..mkv] => [Marvel's Iron Fist - 1x01 - Snow Gives Way]
Group: [tvs:marvels iron fist] => [Netflix.Iron.Fist.S01E01.Snow Gives Way..mkv]
Get [English] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
No matching subtitles found: E:\New\Netflix.Iron.Fist.S01E01.Snow Gives Way..mkv
Rename episodes using [TheTVDB]
Auto-detected query: [Marvel's Iron Fist]
Fetching episode data for [Marvel's Iron Fist]
[MOVE] From [E:\New\Netflix.Iron.Fist.S01E01.Snow Gives Way..mkv] to [E:\TV Shows\Marvel's Iron Fist\Season 1\S01E01 - Snow Gives Way.mkv]
Processed 1 files
Execute: telegram.py -t "*Marvel's Iron Fist*" -m "_S01E01 - Snow Gives Way_ is ready."
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 
Clean clutter files and empty folders
Delete E:\New\output.txt
Done ?(?????)?
```

`TerminatorExpectedAtEndOfString` looks like I'm missing something at the end of the line in args.txt

This is what my `args.txt` (the file which is passed via --def exec=@...) contains:

`telegram.py -t "*{movie}{episode; n}*" -m "{movie; 'The movie'}_{episode; s00e00}{episode; ' - '}{episode; t}_ {movie; 'is ready.'}{episode; "is ready."}"`

**Comment by rednoah** [comment]
The command you generate is not quoted correctly. You can use the `quote()` function to have FileBot quote and escape the value correctly.

e.g.
```
echo quote(n)
```

**Comment by ArionMiles** [comment]
I tried this, and get this:

```
Execute: echo quote(n)
n : The term 'n' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+ echo quote(n)
+            ~
    + CategoryInfo          : ObjectNotFound: (n:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Also, the same string in earlier versions used to run okay.

**Comment by rednoah** [comment]
My bad. This should work:
```
echo {quote(n)}
```

**Comment by ArionMiles** [comment]
Man this makes stuff so much more difficult. Why did you create this in newer versions?

Do you have a help page or forum post on this function? 

I'm trying to pass the `t` `n` `s00e00` as strings into my python script, but they're enclosed in "@" signs.

Here's what I'm trying to pass:
`telegram.py -t "{movie; '*'}{epsiode; '*'}{movie; quote(n)}{episode; quote(n)}{movie; '*'}{epsiode; '*'}" -m "{movie; 'The movie'}{episode; '_'}{episode; quote(s00e00)}{episode; ' - '}{episode; quote(t)}{episode; '_'}{movie; ' is ready.'}{episode; ' is ready.'}"`

and this is the output which is being passed into the python script:
`Execute: telegram.py -t "@'
Marvel's Iron Fist
'@" -m "_@'
S01E01
'@ - @'
Snow Gives Way
'@_ is ready."`

**Comment by rednoah** [comment]
The main difference is that old versions are using `cmd` while newer versions are using `powershell`. This makes things behave better and more like bash.

As for what you're doing wrong, let me give you a simple example:

YES:
```
echo {quote(n)}
```
NO:
```
echo "{quote(n)}"
```

**Comment by rednoah** [comment]
This is easier to maintain, less code, and works on all platforms:
```
telegram.py -t {quote("** $n **")} -m {quote("The $type ** ${any{episode}{movie}} ** is ready.")}
```

**Comment by ArionMiles** [comment]
Have you made documentation of this function? I'd like to know how to format episode naming in this.

I'm trying `{quote("The $type * ${any{episode; s00e00}{episode; t}{movie}} * is ready.")}`
but only the first `episode` argument is being taken. I only get `ShowName The Episode SxxExx is ready.`

**Comment by ArionMiles** [comment]
Okay, I experimented a little bit myself and got what I wanted.

I wanted `SeriesName The SxxExx - EpisodeTitle is ready` and I got this by:

`telegram.py -t {quote("* $n *")} -m {quote("The $type _ ${any{episode; s00e00}{movie}} - ${episode; t} _ is ready.")}`

Thanks for your help! Though, I believe there should be documentation on this function for powershell noobs like me.

**Comment by rednoah** [comment]
The documentation is `String quote(String)`, i.e. the `quote` function takes a String and gives back a String.

The rest is just FileBot Formats and Groovy which is documented in the FileBot Format docs and Groovy docs respectively.

**Comment by ArionMiles** [comment]
This is exactly what I've been looking for. Thanks man! You're correct, this is less code. 

I'm writing a guide for cross-platform torrent automation, so I'd like to know if your solution will work on Linux and Mac OS as well?

**Comment by rednoah** [comment]
Yes, `quote()` will quote for PowerShell on Windows and for bash on Linux and Mac, so as long as your python script is on the $PATH, it'll just work.
