### ISSUE TITLE
Please for the love of God, change that horrible font on your Reviews page.

### ISSUE THREAD

**Issue by ArionMiles** [filebot/filebot#27]
You're using [Dawning of a New Day](https://fonts.google.com/specimen/Dawning+of+a+New+Day) font on your reviews page, which is very un-readable, at such a small font size, especially on my 720p screen.

Please consider moving to a better, more readable font.

**Comment by ArionMiles** [comment]
I suggest you use [Playfair Display.](https://fonts.google.com/specimen/Playfair+Display)

**Comment by rednoah** [comment]
It's meant to look handwritten. I'll consider your suggestion.

**Comment by ArionMiles** [comment]
If you're looking for something handwritten, I found this to be more readable: [Courgette](https://fonts.google.com/specimen/Courgette)

**Comment by rednoah** [comment]
I kinda like how `Dawning of a New Day` looks on the [front page](http://www.filebot.net/). I'll try `Courgette`.
