### ISSUE TITLE
Wrong filename with [rarbg] after release group

### ISSUE THREAD

**Issue by RikuXan** [filebot/filebot#28]
Many RARBG releases have a `[rarbg]` added to the release group (e.g. `TBS[rarbg]`). When using the `{group.ascii()}` binding at the end of a naming rule, this results in the output file being named `...TBS[RARBG.mkv]` with the filesystem cutting the closing bracket, leaving the file named `...TBS[RARBG.mkv`.

I would either propose to leave out the part in brackets (since as far as I understand it, it's not the release group when in brackets, but rather the site which it was distributed to), or pull the closing bracket before the file extension.

Here is an example log: [filebot.log](https://gist.github.com/RikuXan/ea3506af43db96af5c3c0b2c586372c5)

**Comment by rednoah** [comment]
Please provide an example filename and format expression so I can try this myself.

**Comment by RikuXan** [comment]
Sorry, I messed up the example log link, should work now

**Comment by rednoah** [comment]
This particular issue should have been fixed with the latest revision.
