### ISSUE TITLE
WEB not being recognised as a source

### ISSUE THREAD

**Issue by RikuXan** [filebot/filebot#29]
Releases with `WEB` in their name have their `{source}` binding empty. I'm not sure if this is intended behaviour due to the term being too generic or an oversight.

Here is an example log: [filebot.log](https://gist.github.com/RikuXan/ea3506af43db96af5c3c0b2c586372c5)

**Comment by rednoah** [comment]
Here is the pattern of accepted `source` values that match `WEB`:
```
WEBRip|WEB.Rip|WEBDL|WEB.DL|WEBCap|WEB.Cap
```
Adding `WEB` to the list will probably cause a lot of false positives, so for this one I'd recommend checking yourself in your format, e.g. `fn.match(/WEB/)`.
