### ISSUE TITLE
No Scraping/Renaming/Moving with 4.7.1 on Synology

### ISSUE THREAD

**Issue by DKeppi** [filebot/filebot#3]
I used the same files!!!

**Log from 4.7 (works):**

Run script [fn:amc] at [Thu Aug 04 06:38:44 GMT+01:00 2016]
Parameter: ignore = .nfo,.txt,.url,.rar,.jpg,.iso,.idx,.sub
Parameter: seriesFormat = /volume1/video/Serien/{n}/Staffel{s.pad(2)}/{n}.{s00e00}.{t}
Parameter: movieFormat = /volume1/video/Filme/{n} ({y})/{n} ({y})
Parameter: clean = y
Parameter: plex = 127.0.0.1:qEhKSidRZ***************
Argument: /volume1/downloads
Input: /volume1/downloads2016-MULTiPLEX/mp--webdl.mkv
Exclude: /volume1/downloads/ 2016-MULTiPLEX/Gl.to - Dir Art.url
Exclude: /volume1/downloads/2016-MULTiPLEX/mp--webdl.nfo
Exclude: /volume1/downloads/2016-MULTiPLEX/www.gl.to [urls].txt
Exclude: /volume1/downloads/2016-MULTiPLEX/www.gl.to.txt
Exclude: /volume1/downloads/2016-MULTiPLEX/www.gl.to.url
mp--webdl.mkv [series: null, movie:  (2016)]
Group: [tvs:null, mov: 2016] => [mp--webdl.mkv]
Rename movies using [TheMovieDB]
Failed to grep IMDbID: Gt.url
Failed to grep IMDbID: mp--webdl.nfo
Failed to grep IMDbID: l.to.url
Auto-detect movie from context: [/volume1/downloads/ 2016-MULTiPLEX/mp--webdl.mkv]
Stripping invalid characters from new path: /volume1/video/Filme/ (2016)/ (2016)
[MOVE] Rename [/volume1/downloads/2016-MULTiPLEX/mp--webdl.mkv] to [/volume1/video/Filme/ (2016)/ (2016).mkv]
Processed 1 files
Notify Plex: 127.0.0.1
GET: http://127.0.0.1:32400/library/sections/all/refresh?X-Plex-Token=qEhKS***********************+
Clean clutter files and empty folders
Delete /volume1/downloads/2016-MULTiPLEX/G.to - D.url
Delete /volume1/downloads/2016-MULTiPLEX/mp--webdl.nfo
Delete /volume1/downloads/2016-MULTiPLEX/www.el.to [urls].txt
Delete /volume1/downloads/2016-MULTiPLEX/l.to.txt
Delete /volume1/downloads/2016-MULTiPLEX/l.to.url
Delete /volume1/downloads/2016-MULTiPLEX
Done ヾ(＠⌒ー⌒＠)ノ

**Log from 4.7.1 (does not work)**

Run script [fn:amc] at [Thu Aug 04 06:30:26 GMT+01:00 2016]
Parameter: ignore = .nfo,.txt,.url,.rar,.jpg,.iso,.idx,.sub
Parameter: seriesFormat = /volume1/video/Serien/{n}/Staffel{s.pad(2)}/{n}.{s00e00}.{t}
Parameter: movieFormat = /volume1/video/Filme/{n} ({y})/{n} ({y})
Parameter: clean = y
Parameter: plex = 127.0.0.1:qEhKSidRZG****************
Argument: /volume1/downloads
Input: /volume1/downloads/2016-MULTiPLEX/mp--webdl.mkv
Exclude: /volume1/downloads/2016-MULTiPLEX/ - Dt.url
Exclude: /volume1/downloads/2016-MULTiPLEX/mp--webdl.nfo
Exclude: /volume1/downloads/2016-MULTiPLEX/el.to [urls].txt
Exclude: /volume1/downloads/2016-MULTiPLEX/el.to.txt
Exclude: /volume1/downloads/2016-MULTiPLEX/el.to.url
mp--webdl.mkv [series: null, movie: W (2016)]
Group: [tvs:null, mov:w 2016] => [mp--webdl.mkv]
Rename movies using [TheMovieDB]
Index: 0, Size: 0
Clean clutter files and empty folders
Finished without processing any files
Failure (°_°)

**Comment by rednoah** [comment]
Known Issue: https://www.filebot.net/forums/viewtopic.php?f=6&t=4023

**Comment by rednoah** [comment]
FYI, `--def ignore` expects a `regex` so this won't work:
```
Parameter: ignore = .nfo,.txt,.url,.rar,.jpg,.iso,.idx,.sub
```

**Comment by DKeppi** [comment]
THX for this Info!

So it should be a ignore.txt at the same place where my script is?

Parameter: ignore = ignore.txt
In the ignore.txt:
*nfo
*txt
*url
and so on?

**Comment by rednoah** [comment]
The correct usage for matching file extensions would look like this:
```
--def ignore='[.](nfo|txt|url)$'
```

**Comment by DKeppi** [comment]
Thank you!

**Comment by DKeppi** [comment]
I updated my /var/packages/filebot/target/FileBot.jar
with https://sourceforge.net/projects/filebot/files/filebot/HEAD/FileBot.jar
It works again!
