### ISSUE TITLE
Shows with incrementing episode numbers (without season) aren't properly matched

### ISSUE THREAD

**Issue by LeLobster** [filebot/filebot#32]
Wasn't quite sure how to describe this bug in the issue title... but anyway

This bug occurred on Windows 7 with FileBot 4.7.8.

I have a 291 episode show which is ripped as `show name - episode`
where episode is a number from 001 to 291

I'm trying to scrape from thetvdb, and have my files in the exact same structure as the show is found on thetvdb. For each season I've created a folder and I've double checked about having the correct episodes in them.  

Now when I try to scrape thetvdb with FileBot the order is a complete mess.  
For season 1 everything is fine and it assigns the correct episodes, but past season 1 is where it goes wrong.  
Season 2 is mostly detected as a mix of season 7/8 episodes, season 3 and 4 are a mix of 3/4, seasons , seasons 5 and 6 are mostly fine, but then seasons 7, 8 and 9 are a mix of seasons 2, 7 and 8.  And episodes appear in random order.  

In the `original files` section of FileBot all episodes appear in the correct order.

If this is something you want to look into feel free to ask me for any other info you'd like, but if not you can close it and I'll manually assign the correct names.

edit: I just wrote a quick Python script to properly rename the files so that its format is `name - season n episode n` and now scraping thetvdb with FileBot works fine and everything is matched properly. So it definitely was a problem with the filename and not some error from thetvdb API.

**Comment by rednoah** [comment]
Please provide example file names and logs or screenshots.

**Comment by LeLobster** [comment]
I have already processed the files so I couldn't use the originals anymore, but I recreated empty .mkv files with the same name format, and placed them in exactly the same folder structure.  

```
DBZ - 008 - Gohan Goes Banana's.mkv
DBZ - 009 - The Strangest Robot.mkv
...
DBZ - 034 - Krillin's Offensive.mkv
DBZ - 035 - Mercy.mkv
...
DBZ - 077 - The Fusion.mkv
DBZ - 078 - Fighting Power, One Million.mkv
...
DBZ - 290 - Buu's Reincarnation.mkv
DBZ - 291 - Goku's Next Journey.mkv
```

What I think what's causing the bug is that Filebot misinterprets episodes with 2xx as being season 2?  
I also think the random mess I described earlier was a result of me dragging names around and not realizing I did because I was a bit sleepy when I wrote this issue. My apologies.  

Besides seasons 2, 7 and 8 being mixed up I can't recreate any of the 'complete mess' I described.

![0](https://cloud.githubusercontent.com/assets/11016915/26731701/265287e2-47b5-11e7-9b72-70c9a07f2ec2.png)
![1](https://cloud.githubusercontent.com/assets/11016915/26731702/265781de-47b5-11e7-8172-ae0798593e64.png)

No logs because I can't find any in any of the Filebot folders besides an error log which contains nothing relevant to this bug.

**Comment by rednoah** [comment]
I see. Please read [Convert Absolute to SxE numbers](https://www.filebot.net/forums/viewtopic.php?t=2769).

**Comment by LeLobster** [comment]
Oh, I didn't know that was a thing and also didn't know that's called 'absolute' order. My apologies and thank you for your time.

**Comment by rednoah** [comment]
No worries. It's kind of a bug, but it's just not something that can be fixed without rewriting and breaking everything, and the "Match with Absolute, Format with Airdate" workaround is very reliable.
