### ISSUE TITLE
Naming Artwork

### ISSUE THREAD

**Issue by zero77** [filebot/filebot#35]
Can you please add the ability to name art work for instance the poster.jpg to match the name of the film or tv show.
Thanks

**Comment by rednoah** [comment]
No, `poster.jpg` is the standard. But you could just write your own scripts that searches for all the `poster.jpg` and then renames them to match a nearby movie file. ;)

**Comment by zero77** [comment]
Is that possible with filebot or will I need to make a completely separate script.

**Comment by rednoah** [comment]
Yes, this script would be completely independent of FileBot. Though if you write it in `Groovy` then you could use `filebot -script` to run this script. I'd use `groovy` or `bash`, shouldn't be more than a few lines either way.

**Comment by zero77** [comment]
Ok thanks, I will give it a try in bash.
