### ISSUE TITLE
Make easier to install from GitHub Repo?

### ISSUE THREAD

**Issue by mynattc** [filebot/filebot#36]
The next step should be to write a bash script to aid in easy installation for Mac &/or Linux. As it stands it is not very user friendly to install from GitHub.

**Comment by mynattc** [comment]
Current path should be 

filebot/installer/appbundle/MacOS/filebot.sh

**Comment by rednoah** [comment]
The portable Linux version has an install script. The Mac version has the App Store and brew cask which are both a much better options than a bash script from the internet.

GitHub is for developers, not for users, who probably shouldn't execute random bash scripts from the internet anyway. ;)
