### ISSUE TITLE
Add support for WEB

### ISSUE THREAD

**Issue by ri4162** [filebot/filebot#37]
Many new videos are comming withj sources as WEB and filebot leaves it blank.

**Comment by rednoah** [comment]
I'm not you, so you'll have to explain it in a way so somebody that isn't you can understand the problem and the solution you propose. ;)

**Comment by ri4162** [comment]
I do not know how filebot works but I believe in the file ReleaseInfo.properties “pattern.video.source:” should have |WEB| added. 

Most videos are marked with Webrip or Webdl and I have a folder that includes {source} and the folder gets properly named.

As newer videos are coming out just marked as web, filebot doesn’t know what to do with them and leaves them blank. I have a temporary fixed for it now in my naming scheme but something that should be name WEB.720p shows up as .720p and in Linux they are hidden by default. 

I hope I clarified it much better and am on mobile so I can’t send pictures till tomorrow.

**Comment by rednoah** [comment]
Can you give me an example file name? The format you're using? The value you're getting? The value you'd like to get?

**Comment by ri4162** [comment]
Game.of.Thrones.S07E03.720p.WEB.h264-TBS

TV/{source}.{vf}/{n} - {s00e00} - {t}

I get 
TV/.720p/Games of Thrones - S07E03 - XXX.mkv

I want
TV/WEB-DL.720p/Games of Thrones - S07E03 - XXX.mkv

Or
TV/WEB.720p/Games of Thrones - S07E03 - XXX.mkv

**Comment by ri4162** [comment]
“...and the scene (though the scene uses WEB instead of WEB-DL).”

**Comment by rednoah** [comment]
Mmmhhh. Maybe in the future, but right now I'm not inclined to add `WEB` to the `{source}` pattern, because "web" is an English word that can appear in movie names. I'd would probably mess with things there.

For now I guess for now you'll have to handle this special case in your custom format.
