### ISSUE TITLE
Add exception for game of thrones to series-mappings

### ISSUE THREAD

**Issue by gregory-m** [filebot/filebot#38]
I have files named like this:
`GOT (Season 07) DUB 1080/GOT.(S07E01).HD1080.DUB.(qqss44).mkv`

You already have record for Game of Thrones but it doesn't help in may case.

Can you add:
`got	Game of Thrones`
to series-mappings?
Thank you.

**Comment by rednoah** [comment]
Thanks for the example filename. I'll see what I can do.
