### ISSUE TITLE
Is this the official Filebot repository?

### ISSUE THREAD

**Issue by hackel** [filebot/filebot#39]
There are no branches or version tags, no releases, no changelog, yet commits are being made.  What's the actual status of this project?

**Comment by rednoah** [comment]
Yes, this is the official source. The Tag / Release feature of GitHub is not used. The change log is maintained in the forums:
https://www.filebot.net/forums/viewtopic.php?f=7&t=1609

**Comment by sam3d** [comment]
Why was this issue just closed? It's a genuinely good question.

No problem if you're not publishing any build, version, or changelog information (as it is your project). But it'd be more polite to just say "I don't publish that information as I charge for this application and I don't want hand-hold users if/when they attempt use it for free", surely?

**Comment by rednoah** [comment]
OP was rude on reddit so I couldn't be bothered to write a reply.

**Comment by sam3d** [comment]
Ah that makes sense. Thank you for responding anyway!
