### ISSUE TITLE
Filebot not working on symlinked directories, an error of file already exists....

### ISSUE THREAD

**Issue by felisucoibi** [filebot/filebot#40]
Filebot not working on symlinked directories, an error of file already exists.... i'm using buutnu 16.04 and symlinked directories, under these directories filebot can't rename.... it says file already exists....

**Comment by rednoah** [comment]
Can you somehow narrow down the issue? If first-delete-then-create-symlink doesn't work on the filesystem level for some strange reason, what else can FileBot do?

If this is a cross-post from the FileBot Forums, please link the thread.

**Comment by felisucoibi** [comment]
Don't tell me filebot is the first software i found having problems with this.... the rest of the software i'm using since... ever don't have this kind of problems with symlinked directories and files inside. They just work...

**Comment by rednoah** [comment]
The problem is probably caused by canonical paths being cached for a few seconds internally. I'll have a look.

**Comment by rednoah** [comment]
What happens if you set `export JAVA_OPTS="-Dsun.io.useCanonCaches=false -Dsun.io.useCanonPrefixCache=false"` before calling `filebot`?

**Comment by eminga** [comment]
Came here to report the same issue:
`FileAlreadyExistsException: /home/eminga/Videos
java.util.concurrent.ExecutionException: java.nio.file.FileAlreadyExistsException: /home/eminga/Videos
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.nio.file.FileAlreadyExistsException: /home/eminga/Videos
	at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:116)
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:61)
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:22)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:249)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:222)
	at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)`

with `/home/eminga/Videos -> /media/sdb2/Videos/`

The problem only occurs if the file is placed directly in a symlinked directory: `/home/eminga/Videos/video.mp4`
It doesn't occur in this case: `/home/eminga/Videos/test/video.mp4`

Setting `export JAVA_OPTS="-Dsun.io.useCanonCaches=false -Dsun.io.useCanonPrefixCache=false" ` didn't help.

**Comment by rednoah** [comment]
Please run `filebot -script fn:sysinfo` and post the output.

**Comment by eminga** [comment]
`$ ./filebot.sh -script fn:sysinfo
FileBot 4.7.9 (r4991)
JNA Native: 5.1.0
MediaInfo: 0.7.99
Apache Commons VFS: [zip, rar]
Chromaprint: 1.4.2
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2017-05-15 (r500)
Groovy: 2.4.10
JRE: Java(TM) SE Runtime Environment 1.8.0_151
JVM: 64-bit Java HotSpot(TM) 64-Bit Server VM
CPU/MEM: 8 Core / 1 GB Max Memory / 19 MB Used Memory
OS: Linux (amd64)
Package: PORTABLE
uname: Linux l702x 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Done ヾ(＠⌒ー⌒＠)ノ`

**Comment by rednoah** [comment]
Have you tried the latest release for the portable? Install via the latest `portable.sh` and then call `update-filebot.sh` for the latest revision.

**Comment by eminga** [comment]
Just updated to the latest release (somehow missed it, thanks for pointing out), the issue is still there:
```
FileAlreadyExistsException: /home/eminga/Videos
java.util.concurrent.ExecutionException: java.nio.file.FileAlreadyExistsException: /home/eminga/Videos
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:327)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.nio.file.FileAlreadyExistsException: /home/eminga/Videos
	at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:117)
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:62)
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:22)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:249)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:222)
	at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
```
```
$ ./filebot.sh -script fn:sysinfo
FileBot 4.7.13 (r5218)
JNA Native: 5.2.0
MediaInfo: 0.7.99
Apache Commons VFS: [zip, rar]
Chromaprint: 1.4.2
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2017-05-15 (r500)
Groovy: 2.4.12
JRE: Java(TM) SE Runtime Environment 1.8.0_151
JVM: 64-bit Java HotSpot(TM) 64-Bit Server VM
CPU/MEM: 8 Core / 1 GB Max Memory / 20 MB Used Memory
OS: Linux (amd64)
Package: PORTABLE
uname: Linux l702x 4.13.9-200.fc26.x86_64 #1 SMP Mon Oct 23 13:52:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rednoah** [comment]
Please create a small reproducible test case.

It works with symlinks as far as I can tell:
```
$ ln -s Test TestLink
$ touch Test/Firefly.1x01.mp4
$ filebot -rename Test --output TestLink
Rename episodes using [TheTVDB]
Auto-detected query: [Firefly]
Fetching episode data for [Firefly]
[MOVE] From [Test/Firefly.1x01.mp4] to [Test/Firefly - 1x01 - The Train Job.mp4]
Processed 1 files
```

**Comment by eminga** [comment]
Your test case works, but I think that is because it doesn't use the symlinked directory as input. What doesn't work is this:
```
$ mkdir Test
$ ln -s Test TestLink
$ touch Test/Firefly.1x01.mp4
$ filebot -rename TestLink
Rename episodes using [TheTVDB]
Auto-detected query: [Firefly]
Fetching episode data for [Firefly]
[MOVE] from [/home/eminga/TestLink/Firefly.1x01.mp4] to [/home/eminga/TestLink/Firefly - 1x01 - The Train Job.mp4]
[MOVE] Failure: java.nio.file.FileAlreadyExistsException: /home/eminga/TestLink
Processed 0 files
/home/eminga/TestLink
java.nio.file.FileAlreadyExistsException: /home/eminga/TestLink
	at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:117)
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:62)
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:22)
	at net.filebot.cli.CmdlineOperations.renameAll(CmdlineOperations.java:626)
	at net.filebot.cli.CmdlineOperations.renameSeries(CmdlineOperations.java:246)
	at net.filebot.cli.CmdlineOperations.rename(CmdlineOperations.java:121)
	at net.filebot.cli.ArgumentProcessor.runCommand(ArgumentProcessor.java:96)
	at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:26)
	at net.filebot.Main.main(Main.java:111)

Failure (°_°)

# using the non-symlinked directory works:
$ filebot -rename Test
Rename episodes using [TheTVDB]
Auto-detected query: [Firefly]
Fetching episode data for [Firefly]
[MOVE] from [/home/eminga/Test/Firefly.1x01.mp4] to [/home/eminga/Test/Firefly - 1x01 - The Train Job.mp4]
Processed 1 files
```

**Comment by rednoah** [comment]
Fixed with `r5233`.

**Comment by kai23** [comment]
Hi, I also have this error and don't know how to solve it.

I have a medialibrary, and this symlink exists, but is broken : 

```
/medialibrary/Movies/Action ou Vérité (2018)/Action ou Vérité (2018).mkv
```

I created a simple `fetch.sh` which is exactly like this : 

```
#!/bin/bash

export JAVA_OPTS="-Xmx256m -Dsun.io.useCanonCaches=false -Dsun.io.useCanonPrefixCache=false"

/home/flo/utils/rename/test/filebot.sh --lang fr -script fn:amc --output "/medialibrary" --log-file "/home/flo/utils/rename/amc.log" --action symlink --conflict override -non-strict --def plex=localhost:yx4sR1jmsBGjcJyYRE39 --def music=n artwork=n "ut_dir=$1" "ut_kind=multi" minFileSize=0
```
 And when I use it this way : 

```
/home/flo/utils/rename/test/fetch.sh /downloads/Truth\ or\ Dare\ \(2018\)\ VF2-ENG\ AC3\ BluRay\ 1080p\ x264.GHT.mkv
```

It fails.

here is the log : 

```
Locking /home/flo/utils/rename/amc.log
Run script [fn:amc] at [Sat Sep 01 20:21:12 CEST 2018]
Parameter: plex = *****
Parameter: music = n
Parameter: artwork = n
Parameter: ut_dir = /downloads/Truth or Dare (2018) VF2-ENG AC3 BluRay 1080p x264.GHT.mkv
Parameter: ut_kind = multi
Parameter: minFileSize = 0
Input: /downloads/Truth or Dare (2018) VF2-ENG AC3 BluRay 1080p x264.GHT.mkv
Group: [mov:truth or dare 2018] => [Truth or Dare (2018) VF2-ENG AC3 BluRay 1080p x264.GHT.mkv]
Rename movies using [TheMovieDB]
Auto-detect movie from context: [/downloads/Truth or Dare (2018) VF2-ENG AC3 BluRay 1080p x264.GHT.mkv]
[SYMLINK] from [/downloads/Truth or Dare (2018) VF2-ENG AC3 BluRay 1080p x264.GHT.mkv] to [/medialibrary/Movies/Action ou Vérité (2018)/Action ou Vérité (2018).mkv]
[SYMLINK] Failure: java.nio.file.FileAlreadyExistsException: /medialibrary/Movies/Action ou Vérité (2018)/Action ou Vérité (2018).mkv
Processed 0 files
FileAlreadyExistsException: /medialibrary/Movies/Action ou Vérité (2018)/Action ou Vérité (2018).mkv
Finished without processing any files
Failure (°_°)
```

And the sysinfos : 

```
./filebot.sh -script fn:sysinfo                                                                                                                  1 ↵
FileBot 4.8.2 (r5789)
JNA Native: 5.2.2
MediaInfo: 18.05
7-Zip-JBinding: 9.20
Chromaprint: java.io.IOException: Cannot run program "fpcalc": error=2, No such file or directory
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2018-08-14 (r534)
Groovy: 2.5.1
JRE: OpenJDK Runtime Environment 1.8.0_181
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 8 Core / 6 GB Max Memory / 20 MB Used Memory
OS: Linux (amd64)
HW: Linux aircotyovh 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
DATA: /home/flo/utils/rename/test/data/flo
Package: TAR
License: FileBot License P4416584 (Valid-Until: 2019-09-01)
```

**Comment by rednoah** [comment]
Maybe fixed with `r5849`.
