### ISSUE TITLE
[Bug] Artwork Not Working

### ISSUE THREAD

**Issue by zero77** [filebot/filebot#41]
When I use filebot to fetch artwork it finds and downloads it but, the poster and sometimes some of the other files are 0 kb in size and unusable.

I am using the newest stable filebot on Ubuntu also. 
I am not getting any errors but hear is a screenshot of the outputted files, the blue files are 0 kb:

![capture](https://user-images.githubusercontent.com/16563034/30909066-b095b712-a377-11e7-8308-0c8d23f0f566.JPG)

Also the tvdb supports https and filebot is using http.
Thanks

**Comment by rednoah** [comment]
Thanks for the bug report. Fixed with the latest revision. Please wait for the next release.

**Comment by zero77** [comment]
Thanks, is there a portable linux package.

**Comment by rednoah** [comment]
Does the portable install script not work?
https://github.com/filebot/plugins/blob/master/installer/portable.sh

**Comment by zero77** [comment]
I checked the script and after running it, when I check the file bot version in terminal it hasn’t updated.

But, when I run filebot from /usr/local/bin/filebot it has updated so, I think the “# Link into default $PATH” needs a second line with another directory but, I am not sure which one yet.

Also, the script doesn’t seam to clean up after its self.

**Comment by zero77** [comment]
Both /usr/share/filebot and /usr/bin/filebot seam to have out of date filebots in.
