### ISSUE TITLE
[Bug] FileBot Bash Script

### ISSUE THREAD

**Issue by zero77** [filebot/filebot#42]
I am running a rename bash script in Ubuntu with filebot 4.7.11 portable it has stopped working and now I am getting an error saying “Error during startup: ExceptionInInitializerError” which prevents me running the script at all.
Thanks

**Comment by rednoah** [comment]
Does it say anything other than `Error during startup: ExceptionInInitializerError`. The complete console output would be helpful.

**Comment by zero77** [comment]
Its just that error then it stops.

**Comment by zero77** [comment]
It seems to work if I run the script as sudo although, that now stops me automatically loading the script from a torrent client as it needs a password.

**Comment by rednoah** [comment]
Did you previously run `filebot` as root? If you run it as root for the first them, then all data files will be created with root permissions making it impossible for normal users to call filebot later on, depending on your settings.

What does the sysinfo output say?

**Comment by zero77** [comment]
No I normally run it as a standard user until I got this error when I found running it as sudo/root helps. 

What sysinfo output do you mean, do you mean the file permissions, and if so for which ones the outputted or inputted files or the script calling filebot or the filebot.sh

**Comment by zero77** [comment]
Thank you
But I have fixed it the initial filebot update script was giving everything root permissions.
