### ISSUE TITLE
Formatting Error 

### ISSUE THREAD

**Issue by zero77** [filebot/filebot#43]
When I try to use either {resolution} or {hpi} or {vf} I am getting a message saying they have not been set.
Can you please define these by default in binding reference.

i am using filebot 4.7.13 portable in Linux

Thanks

**Comment by rednoah** [comment]
Did you select a valid sample file that FileBot can retrieve those values from?

https://www.filebot.net/forums/viewtopic.php?f=5&t=4285

**Comment by zero77** [comment]
Thanks for the reply, I have given that a go and the media file is missing when I Open MediaInfo under edit format.

It this not automatically done when filebot is staled or updated.

**Comment by rednoah** [comment]
FileBot does not ship with a ~700 MB sample media file. You have to select the media file you want to test with yourself.

**Comment by zero77** [comment]
Where is the media file located on Ubuntu or where can I obtain it from.

**Comment by rednoah** [comment]
Any media file. It's your media file that you want to use for testing. If you use different files then you get different values.

Presumably, there's no actual bug or issue, so I'm closing this now. Play with it. You'll figure it out.

**Comment by zero77** [comment]
Ok thanks I will give it a go.
