### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by seitzbg** [filebot/filebot#46]
How do I purchase this application to run on Linux?

**Comment by rednoah** [comment]
Linux is not supported. You can join the Patreon if Linux support is something you'd like to see:
https://www.patreon.com/filebot

**Comment by bachp** [comment]
@rednoah What exactly do you mean by Linux is not supported? I think there is a Docker image and an Ubunut package. Also for version 4.7.9 there was an [Arch Linux Package](https://aur.archlinux.org/packages/filebot/) available. However it seems there haven't been any new releases since then.

**Comment by rednoah** [comment]
Yes. `FileBot 4.7.9` is still available for you to use. It's provided as is and not officially supported.

The latest officially supported release is only available as a paid purchase on the App Store.

**Comment by rednoah** [comment]
I'd like to spend time on Linux support, but if there's only a total of `9` users that can be bothered to support my Patreon, then I can't be bothered to support Linux. 🐬

**Comment by ashmandias** [comment]
If you set a more reasonable monthly goal, many, myself included, would happily chip in. $1k/month seems a bit high for an initial goal. It's my understanding that patreon doesn't roll over, so there is not much incentive to chip in -- that said, 35 people evidently chipped in int he last 6 days despite that fact....

**Comment by rednoah** [comment]
The goal is `$1` *PER RELEASE* so I'll be collecting `$3` or `$4` dollars per year.

FileBot has been around for 10 years, and if there aren't at least 1000 users willing to chip in at least `$1` then there's absolutely no point in continued support. IMHO, `$1000` per release (or per month for that matter) is extremely reasonable.

**Comment by ashmandias** [comment]
Fair enough -- I have not run itno a non-monthly patreon before this.

**Comment by rednoah** [comment]
No worries. I guess I should write that more clearly. I've never done a Patreon before. They don't even have a software category.

**Comment by 2devnull** [comment]
Is this the reason the links to 4.7.9 portable jars are broken?

**Comment by rednoah** [comment]
No. What does the log say?

**Comment by 2devnull** [comment]
it's not the log, it's on sourceforge, the links seems dead.

**Comment by rednoah** [comment]
Which link? What does `curl` say when you download the file?

**Comment by 2devnull** [comment]
I guess this one:
https://sourceforge.net/projects/filebot/files/filebot/File_4.7.9/FileBot_4.7.9-portable.tar.xz

even this one:
https://get.filebot.net/filebot/latest/FileBot.jar.xz.gpg

Everything seems broken and fragmented. What is going on?

**Comment by 2devnull** [comment]
I was able to locate it somewhere else.

**Comment by pfeerick** [comment]
Just confirming it isn't a one-off issue... I have on two seperate occasions about two months apart hit the same error from sourceforge - and no error from curl as sourceforge automatically redirects to the project root and simply says the file is not available... so I also had to grab it directly from one of the sourceforge mirrors when I needed to re-setup filebot a few months ago... 
![image](https://user-images.githubusercontent.com/5500713/38728553-8c566946-3f53-11e8-8e86-7da56922aed1.png)

**Comment by rjsachse** [comment]
What about a portable version 4.8

I have donated well when or if a release happens and just need the new -exec function. 

I wanna support dev's but i guess i should compile from source.

A huge thanks for all that has made the best easiest media sorting tool around.

There is alot of mis-understanding about how the patreon system works (i was one)

**Comment by felisucoibi** [comment]
I'm a linux user, i like to send bugs to make a free software project to grow, even if the owner wants to sell in oficial shops a one click solution.... but if i cant get a .jar with latest version from github, i will not submit the bugs....

**Comment by ashmandias** [comment]
I'm also having a hard time understanding what extra effort is involved with releasing the jar files on Linux -- aren't the jar files the same as on Windows?

**Comment by rednoah** [comment]
Please read this thread:
https://www.filebot.net/forums/viewtopic.php?f=11&t=5734

**Comment by rednoah** [comment]
Linux Support:
https://www.filebot.net/forums/viewtopic.php?f=6&t=6006
