### ISSUE TITLE
Portable installer broken?

### ISSUE THREAD

**Issue by RajatNair** [filebot/filebot#47]
Trying to install portable version and download fails with a 404. 

> curl 'http://get.filebot.net/filebot/latest/FileBot.tar.xz.gpg' 
> 
> HTTP/1.1 404 Not Found
> Date: Sat, 31 Mar 2018 21:45:25 GMT
> Content-Type: text/html
> Content-Length: 30
> 

Is it down or is portable support being removed?

**Comment by rednoah** [comment]
Sorry, nightly builds (for testing the latest revision) are no longer available.
