### ISSUE TITLE
No .jar with latest version for free from github, no bug reports for free in github...

### ISSUE THREAD

**Issue by felisucoibi** [filebot/filebot#50]
Hi i'm filebot linux user, i reported one or two bugs, and the way how to reproduce them, i have 3 more, that hangs completely filebot and is very easy to reproduce them, but if there is no .jar to download with latest version from github, there is no free bug reports.... give to the comunity receive from the community... is a pitty i helped to fix a few bugs, and now i¡'cant download latest version if i don't donate or pay.... you have a good product, because community helped to make this soft to grow, if you use the community return to the community. bests.

**Comment by rednoah** [comment]
FileBot now fully supported on all platforms again, aligning interests of users and developers, but not free:
https://www.filebot.net/forums/viewtopic.php?f=6&t=6006
