### ISSUE TITLE
Building revision 5949 with openjfx 11 fails

### ISSUE THREAD

**Issue by finitelife** [filebot/filebot#56]
Build fails to find javafx on compilation

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

>java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)

>javac -version
javac 11.0.1
>apt list openjfx
Listing... Done
openjfx/cosmic,now 11+26-4 amd64 [installed]

>git rev-parse HEAD
ef6ad3739102ec90057adf79cc5b22558c1a27ba

>ant resolve
...BUILD FAILED...
...build.xml:880: Problem: failed to create task or type antlib:org.apache.ivy.ant:retrieve...

>ant -lib /usr/share/java resolve
...BUILD SUCCESSFUL...

>ant jar
...SwingUI.java:60: error: package javafx.application does not exist...
...[javac] 80 errors...
...BUILD FAILED...
...build.xml:272: Compile failed; see the compiler error output for details....

>ant -lib /usr/share/java jar
...SwingUI.java:60: error: package javafx.application does not exist...
...[javac] 80 errors...
...BUILD FAILED...
...build.xml:272: Compile failed; see the compiler error output for details....

>ant -lib /usr/share/java \
-lib /usr/share/java/javafx.base.jar \
-lib /usr/share/java/javafx.controls.jar \
-lib /usr/share/java/javafx.fxml.jar \
-lib /usr/share/java/javafx.graphics.jar \
-lib /usr/share/java/javafx.media.jar \
-lib /usr/share/java/javafx.swing.jar \
-lib /usr/share/java/javafx.web.jar \
-lib /usr/share/openjfx/lib \
-lib /usr/share/openjfx/lib/javafx.base.jar \
-lib /usr/share/openjfx/lib/javafx.controls.jar \
-lib /usr/share/openjfx/lib/javafx.fxml.jar \
-lib /usr/share/openjfx/lib/javafx.graphics.jar \
-lib /usr/share/openjfx/lib/javafx.media.jar \
-lib /usr/share/openjfx/lib/javafx.swing.jar \
-lib /usr/share/openjfx/lib/javafx.web.jar \
-lib /usr/share/maven-repo/org/openjfx \
-lib /usr/share/maven-repo/org/openjfx/javafx.base.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.controls.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.fxml.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.graphics.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.media.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.swing.jar \
-lib /usr/share/maven-repo/org/openjfx/javafx.web.jar \
-lib ~/Downloads/javafx-sdk-11.0.1/lib \
-lib /usr/lib/jvm/java-11-openjdk-amd64/lib \
jar
...SwingUI.java:60: error: package javafx.application does not exist...
...[javac] 80 errors...
...BUILD FAILED...
...build.xml:272: Compile failed; see the compiler error output for details...

**Comment by rednoah** [comment]
Sorry, source code is available for educational purposes as is. Technical support is not available.

Please download one of the official builds if you would like to use FileBot:
https://www.filebot.net/#download

**Comment by rednoah** [comment]
If you would like to try the latest and greatest, here are builds from today:
https://www.filebot.net/forums/viewtopic.php?f=6&t=9535

**Comment by finitelife** [comment]
Sorry, I was trying to assist by reporting. I've been following all the commits. I am aware that the jdk11 build is a mess, just thought I'd report what I can. I do try the nightlies, and the provided deb does work.

**Comment by rednoah** [comment]
No worries. Build is tricky due to recent changes. Trying the latest beta once in a while is much appreciated though.

**Comment by finitelife** [comment]
fixed with some mangling on r6050!
again, this is for informational purposes only as I found little information on this elsewhere.
here's the changes since last post:

java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu3.18.10.1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu3.18.10.1, mixed mode, sharing)

git rev-parse HEAD
637b720fffdd9367e2410fc3ee2f1ff5b0e4c254

#---ADD OpenJFX (NOT MEDIA,FXML)---
cp /usr/share/java/javafx-{base,swing,controls,graphics,web}.jar lib/jars/
echo -e "\njars/javafx-base.jar\njars/javafx-controls.jar\njars/javafx-graphics.jar\njars/javafx-swing.jar\njars/javafx-web.jar" >> lib/jar.includes

#---ADDED REQUIRED API KEYS (FOR TESTING)---
(will not post)

#compile!
ant -lib /usr/share/java resolve jar deb-universal

#---INSTALL OUR FILEBOT---
sudo dpkg -i dist/FileBot_*_universal.deb

#--TEST--
filebot -script fn:sysenv
# Environment Variables #
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_MEASUREMENT: en_CA.UTF-8
XAUTHORITY: ~/.Xauthority
LC_TELEPHONE: en_CA.UTF-8
XDG_DATA_DIRS: /usr/share/xfce4:/usr/share/xubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop:/usr/share
GDMSESSION: xubuntu
MANDATORY_PATH: /usr/share/gconf/xubuntu.mandatory.path
LC_TIME: en_CA.UTF-8
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
DEFAULTS_PATH: /usr/share/gconf/xubuntu.default.path
XDG_CURRENT_DESKTOP: XFCE
SSH_AGENT_PID: 26066
CLUTTER_BACKEND: x11
COLORTERM: truecolor
LC_PAPER: en_CA.UTF-8
SESSION_MANAGER: local/laptop:@/tmp/.ICE-unix/26084,unix/laptop:/tmp/.ICE-unix/26084
LOGNAME: user
PWD: ~/filebot
LANGUAGE: en_CA
WINDOWID: 88080387
SHELL: /bin/bash
LC_ADDRESS: en_CA.UTF-8
OLDPWD: ~
GTK_MODULES: appmenu-gtk-module
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session1
XDG_SESSION_DESKTOP: xubuntu
SHLVL: 1
LC_IDENTIFICATION: en_CA.UTF-8
GLADE_CATALOG_PATH: :
LC_MONETARY: en_CA.UTF-8
TERM: xterm-256color
XDG_CONFIG_DIRS: /etc/xdg/xdg-xubuntu:/etc/xdg:/etc/xdg
GLADE_PIXMAP_PATH: :
LANG: en_CA.UTF-8
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_ID: c5
XDG_SESSION_TYPE: x11
DISPLAY: :0.0
LC_NAME: en_CA.UTF-8
_: /usr/bin/filebot
GDM_LANG: en_CA
UBUNTU_MENUPROXY: 1
XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/user
GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
DESKTOP_SESSION: xubuntu
USER: user
XDG_MENU_PREFIX: xfce-
VTE_VERSION: 5401
QT_ACCESSIBILITY: 1
LC_NUMERIC: en_CA.UTF-8
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
XDG_SEAT: seat0
GLADE_MODULE_PATH: :
GTK_OVERLAY_SCROLLING: 0
QT_QPA_PLATFORMTHEME: gtk2
XDG_VTNR: 7
XDG_RUNTIME_DIR: /run/user/1000
HOME: ~
# Java System Properties #
awt.toolkit: sun.awt.X11.XToolkit
java.specification.version: 11
sun.cpu.isalist: 
sun.jnu.encoding: UTF-8
java.class.path: /usr/share/filebot/jar/filebot.jar
java.vm.vendor: Oracle Corporation
grape.root: ~/.filebot/grape
useExtendedFileAttributes: true
sun.arch.data.model: 64
jna.library.path: /usr/lib/x86_64-linux-gnu/jni
java.vendor.url: http://java.oracle.com/
user.timezone: 
jna.nounpack: true
os.name: Linux
java.vm.specification.version: 11
sun.net.client.defaultReadTimeout: 60000
jna.boot.library.path: /usr/lib/x86_64-linux-gnu/jni
sun.java.launcher: SUN_STANDARD
user.country: CA
sun.boot.library.path: /usr/lib/jvm/java-11-openjdk-amd64/lib
sun.java.command: /usr/share/filebot/jar/filebot.jar -script fn:sysenv
jdk.debug: release
useGVFS: true
sun.cpu.endian: little
user.home: ~
user.language: en
java.specification.vendor: Oracle Corporation
jdk.module.path: /usr/share/openjfx/lib
net.filebot.Archive.extractor: SevenZipExecutable
java.version.date: 2018-10-16
java.home: /usr/lib/jvm/java-11-openjdk-amd64
file.separator: /
java.vm.compressedOopsMode: 32-bit
line.separator: 
unixfs: false
useCreationDate: false
java.specification.name: Java Platform API Specification
java.vm.specification.vendor: Oracle Corporation
jna.boot.library.name: jnidispatch.system
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
application.cache: ~/.filebot/cache
net.filebot.UserFiles.fileChooser: JavaFX
http.agent: FileBot/4.8.5
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
java.runtime.version: 11.0.1+13-Ubuntu-3ubuntu3.18.10.1
user.name: user
sun.net.client.defaultConnectTimeout: 10000
path.separator: :
java.net.useSystemProxies: true
os.version: 4.18.0-13-lowlatency
jna.nosys: true
java.runtime.name: OpenJDK Runtime Environment
file.encoding: UTF-8
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: http://bugreport.java.com/bugreport/
java.io.tmpdir: ~/.filebot/tmp
swing.crossplatformlaf: javax.swing.plaf.nimbus.NimbusLookAndFeel
java.version: 11.0.1
user.dir: ~/filebot
os.arch: amd64
java.vm.specification.name: Java Virtual Machine Specification
net.filebot.gio.GVFS: /run/user/1000/gvfs
java.awt.printerjob: sun.print.PSPrinterJob
sun.os.patch.level: unknown
application.deployment: deb
java.library.path: /usr/lib/x86_64-linux-gnu/jni
java.vendor: Oracle Corporation
java.vm.info: mixed mode, sharing
java.vm.version: 11.0.1+13-Ubuntu-3ubuntu3.18.10.1
application.dir: ~/.filebot
sun.io.unicode.encoding: UnicodeLittle
org.apache.commons.logging.Log: org.apache.commons.logging.impl.NoOpLog
java.class.version: 55.0
# Arguments #
args[0] = -script
args[1] = fn:sysenv
Done ヾ(＠⌒ー⌒＠)ノ

filebot -script fn:sysinfo
FileBot 4.8.5 (r6050)
JNA Native: 5.2.2
MediaInfo: 18.03.1
p7zip: Version 16.02 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (30678),ASM)
Chromaprint: 1.4.3
Extended Attributes: OK
Unicode Filesystem: OK
GVFS: PlatformGVFS [/run/user/1000/gvfs]
Script Bundle: 2019-02-02 (r543)
Groovy: 2.5.5
JRE: OpenJDK Runtime Environment 11.0.1
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 2 Core / 468 MB Max Memory / 21 MB Used Memory
OS: Linux (amd64)
HW: Linux laptop 4.18.0-13-lowlatency #14-Ubuntu SMP PREEMPT Wed Dec 5 12:12:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
DATA: ~/.filebot
Package: DEB
License: UNREGISTERED
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by rednoah** [comment]
The easy way would be to just patch the release you have with the latest jar from here, which is built every other day, whenever something important changes and need testing:
https://www.filebot.net/forums/viewtopic.php?f=7&t=1609
