### ISSUE TITLE
Repo clone size (vs actual) indicates possible need of maintenance

### ISSUE THREAD

**Issue by CollinChaffin** [filebot/filebot#60]
Cloning this repo of strictly smaller source-code files (no large media files) currently results in a significantly larger local directory then necessary (over half a GIG vs the 37mb actual).  The local clone consists of large object pack file(s) which is almost always an indicator of needed repo maintenance.

To list the 10 largest files, execute this in the repo root directory:
```
git verify-pack -v .git/objects/pack/pack-<FILL-IN-EXISTING-FILENAMES>.idx | sort -k 3 -n | tail -10
```
So in the case of this repo:
```
git verify-pack -v .git/objects/pack/pack-d5658117095795b048340e101d37063e2389ced3.idx | sort -k 3 -n | tail -10

49a4b802561cb56c7dc476ff40e23779a978e0c9 blob   10466977 9623239 243710362
bdf82fdf61cbbe35dec596dd2d2c8f5240e56418 blob   11116688 3902592 352843009
066eb5dbfde24c041b78a44b1dbf678c0a35fd1e blob   12696232 4520692 283117275
d5135544688eee55fa196ef827dd8de91fa0a98c blob   13699408 4846660 220163026
4eb8c49ce88816c3d47b5bc1eff531809d6225c8 blob   14930544 5368525 95649547
677cd2f5c3cfcb7881e6d2ad2d5da755e9142076 blob   15006480 5429636 52578175
caed743fe85fc05c98b15ab182f2bb87d22aa962 blob   15321024 6107422 25487932
9aac5caeaf467ce1fddcdefc14ca6feea8b0015f blob   15366400 5428200 116581651
9c032264824d4178f61ddb5e145a33f23aa5ddae blob   15518928 5389778 185139467
b74cbfd553157d8ba2b6d6b7d1d27f113a3dd75a blob   15555872 5389525 131799803
```
To determine the file name associated with each blob:
```
git rev-list --objects --all | grep [first few chars of each file blob sha1 from previous output]
```

So in the case of this repo:
```
$ git rev-list --objects --all | grep 49a4b802
49a4b802561cb56c7dc476ff40e23779a978e0c9 lib/icu4j.jar

$ git rev-list --objects --all | grep bdf82fdf6
bdf82fdf61cbbe35dec596dd2d2c8f5240e56418 lib/native/mac-x86_64/libmediainfo.dylib

$ git rev-list --objects --all | grep 4eb8c49c
4eb8c49ce88816c3d47b5bc1eff531809d6225c8 lib/native/mac-x86_64/libmediainfo.dylib

$ git rev-list --objects --all | grep 9aac5cae
9aac5caeaf467ce1fddcdefc14ca6feea8b0015f lib/native/mac-x86_64/libmediainfo.dylib

$ git rev-list --objects --all | grep b74cbfd55
b74cbfd553157d8ba2b6d6b7d1d27f113a3dd75a lib/native/mac-x86_64/libmediainfo.dylib
```
As you can see already a pattern of possible artifacts in need of pruning.

The next steps would be to clean up the repo and possibly do some pruning etc.

One option is to use the bfg-repo-cleaner tool found here https://rtyley.github.io/bfg-repo-cleaner/

Otherwise, below are the manual steps as laid out by this official git article: https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery
```
git filter-branch --index-filter 'git rm --cached --ignore-unmatch <FILENAME/TYPE-GOES-HERE>' -- --all
rm -Rf .git/refs/original
rm -Rf .git/logs/
git gc --aggressive --prune=now
```
Repeat (if necessary) for other types of files

When complete, verify:
```
git count-objects -v
```
The pack file(s) should be significantly reduced in size.

The last step - IF AND ONLY IF YOU ARE HAPPY WITH THE LOCAL RESULTS - would be to issue a push:
```
git push origin --force
```
Again this is just a compilation of the official Git info as to how to deal with it but since the size is already exponentially so artificially high for such a small repo I thought I would offer the info as something to possibly start considering.

**Comment by rednoah** [comment]
I'm not in favor of deleting history. `git clone --depth=1` will do the job if you just want the latest revision without history.

Fairly quick:
```
time git clone --depth=1 https://github.com/filebot/filebot.git
Cloning into 'filebot'...
remote: Enumerating objects: 1101, done.
remote: Counting objects: 100% (1101/1101), done.
remote: Compressing objects: 100% (1049/1049), done.
remote: Total 1101 (delta 57), reused 558 (delta 22), pack-reused 0
Receiving objects: 100% (1101/1101), 36.25 MiB | 5.16 MiB/s, done.
Resolving deltas: 100% (57/57), done.

real	0m11.963s
user	0m3.008s
sys	0m1.080s
```

Fairly small:
```
$ du -h filebot | tail -n1
128M	filebot
```
