### ISSUE TITLE
build process jar.includes/jar.jdk8.includes missing

### ISSUE THREAD

**Issue by xorbeat** [filebot/filebot#61]
I'm not able to compile anymore the project since the big cleanup at commit [95d9784464c605c092d826ff2caed18e3b2c3571](https://github.com/filebot/filebot/commit/95d9784464c605c092d826ff2caed18e3b2c3571).
There is no more jar.groovy or jar.includes required from build.xml.
I'm trying with jdk8.patch, no jar.jdk8.includes neither.
How do you compile ? Is something I missing ?

**Comment by rednoah** [comment]
You can now pick and choose the dependencies, includes, excludes, etc to best suite your requirements and build target.

Note that this repository is `source` only and any 3rd party libraries, tools, binaries, etc that you might need for `build` or `package` tasks are not necessarily included.

**Comment by rednoah** [comment]
If you're looking for the latest revision, then I recommend using the official binaries:
https://get.filebot.net/filebot/BETA/

**Comment by xorbeat** [comment]
Ok thanks for your response.
Pity the OpenSource spirit is like under de-construction here...

**Comment by rednoah** [comment]
It is a fine line to walk, if you wanna be open-source and sustainable. ;)

If you have any comments on the code or ideas for improvements to make things work better for your needs, I'm of course happy to discuss and implement code changes.

If you're just looking for a build without interest in the underlying code base, then official binary builds are the way to go.

**Comment by xorbeat** [comment]
I began analyse with some movie matching error and try to understand the implem to maybe fix something.
Thanks for your great job.
Note : I've fixed the build from my side.

**Comment by rednoah** [comment]
Sure thing. Please share your findings when convenient.

**Comment by rednoah** [comment]
If you have matching issues, please also post the `file paths` and `logs` in the FileBot Forums:
https://www.filebot.net/forums/viewtopic.php?f=5&t=1868
