### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by abdelkrimdev** [filebot/filebot#7]
Hello,

The context menu in partucular and the UI in general are a little bit messy

i hope you do something to improve the user experience of the software

Thanks :)

**Comment by rednoah** [comment]
Specific ideas for possible solutions that would make it less messy would be appreciated.

**Comment by abdelkrimdev** [comment]
Hello again :)
first of all thank you very much for your hard work
I really apreaciate what you are doing here
and sorry if i was a little bit rude with you when i said 'messy'
please take a look [here](https://1drv.ms/i/s!AqcvR8rk_8rggq8R7boOKMOBfG5moQ)
this happen when i click in the setting button

**Comment by rednoah** [comment]
Popups shouldn't be displayed outside of the screenbounds, but I guess the underlying frameworks are buggy in this case. A future update of Windows or Java will probably fix this.

As a workaround, I suggest right-clicking the `Rename` and `Match` buttons to access the `Fetch Data` and `Rename Options` popups.
